title: Il Mio Sito di Videogiochi
description: Notizie, recensioni e guide dal mondo dei videogiochi
theme: minima

# Imposta il permalink senza date
permalink: /:collection/:title/

# Definizione delle collections
collections:
  news:
    output: true
    permalink: /news/:title/
  recensioni:
    output: true
    permalink: /recensioni/:title/
  guide:
    output: true
    permalink: /guide/:title/

# Impostazioni generali
author: "Il Mio Nome"
lang: it
